local_costmap:
  global_frame: odom_base_link
  robot_base_frame: lidar_base_link
  update_frequency: 2.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 15
  height: 15
  resolution: 0.2
